name: Build docker image

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    - "v[0-9]+.[0-9]+.[0-9]+-alpha"
    - "v[0-9]+.[0-9]+.[0-9]+-beta"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - run: echo ${{matrix.os}}
      
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build image
        run: docker build -t dotnet-6-plus-node-16 .
      
      - name: Tag latest image
        run: docker tag dotnet-6-plus-node-16 brammys/dotnet-6-plus-node-16:latest
        
      - name: Publish latest image
        run: docker push brammys/dotnet-6-plus-node-16:latest
        
      - name: Tag image with version tag
        run: docker tag brammys/dotnet-6-plus-node-16:latest brammys/dotnet-6-plus-node-16:${{ steps.get_version.outputs.VERSION }}
        
      - name: Publish image with version tag
        run: docker push brammys/dotnet-6-plus-node-16:${{ steps.get_version.outputs.VERSION }}
