name: Build docker image

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - run: echo ${{matrix.os}}
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build image
        run: docker build -t dotnet-6-plus-node-16 .
      
      - name: Tag image
        run: docker tag dotnet-6-plus-node-16 brammys/dotnet-6-plus-node-16:latest
        
      - name: Publish image
        run: docker push brammys/dotnet-6-plus-node-16:latest
        
